apiVersion: v1
kind: Service
metadata:
  name: apache-lb-service # name of the service
spec:
  type: LoadBalancer # type of service (ClusterIP, NodePort, or LoadBalancer)
  selector:
    app: apache # selector for managing all pods with this tag
  ports:
    - port: 80 # open port 80 at lb, creates SG
      targetPort: 80 # Backend POD port