apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache # tags
spec:
  replicas: 2 # replicas of the pods running at all times
  selector:
    matchLabels:
      app: apache # manage all pods with this tag
  template: # template for the pods
    metadata:
      labels:
        app: apache # launch pods with this label
    spec:
      containers:
      - name: apache-container # name of the container
        image: omyro/olga_apache:v2 # image to pull from dockerhub
        ports:
        - containerPort: 80
